### ISSUE TITLE
No charts found containing

### ISSUE THREAD

**Issue by eicnix** [technosophos/vscode-helm#2]
When I click onto a file inside a chart I get the following error: `No charts found containing /path/.../chart/templates/_helpers.tpl`

This error is also printed on the command line: 

```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at vscode.window.onDidChangeActiveTextEditor (/Users/lukaseichler/.vscode/extensions/technosophos.vscode-helm-0.0.1/out/src/extension.js:68:14)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:346482
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at t.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:300894)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:266424)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:154927)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:155604)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

During startup I am also getting this error and the file does not exist. 

```
Error: ENOENT: no such file or directory, open '/Users/lukaseichler/.vscode/extensions/technosophos.vscode-helm-0.0.1/language-configuration.json'
(anonymous) @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

**Comment by technosophos** [comment]
Okay, I am pretty sure that I fixed the first one.

The second one _appears_ to have been a packaging error, so I re-generated the package as well. I haven't been able to reproduce it locally.

**Comment by eicnix** [comment]
I am getting no error anymore but only `No active editor`in the helm output.

**Comment by technosophos** [comment]
Okay. That is a debugging message that I will remove.

**Comment by eicnix** [comment]
Ok. I'll close this issue then.

**Comment by scottrigby** [comment]
@technosophos Love the extension - and was dismissing these errors all day yesterday. I was finally about to open an issue for this Today until I saw this. Updating to `vscode-helm 0.1.1` fixed the issue 👍
